check for lockfile

diff --git a/.github/actions/cached-deps/action.yml b/.github/actions/cached-deps/action.yml
--- a/.github/actions/cached-deps/action.yml
+++ b/.github/actions/cached-deps/action.yml
@@ -3,6 +3,13 @@ description: "Get the dependencies (via npm) and cache them."
 runs:
   using: "composite"
   steps:
+    - name: Check for lockfile
+        run: |
+          if [ ! -f package-lock.json ]; then
+            echo "❌ package-lock.json not found."
+            exit 1
+          fi
+        shell: bash
     - name: Cache dependencies
       id: cache
       uses: actions/cache@v3
